name: blogo

services:
  api:
    build:
      target: development
    networks:
      - app-network
    ports:
      - "${API_EXTERNAL_PORT}:8080"
    environment:
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=${DB_HOST}
      - PGPORT=${DB_PORT}
      - PGDATABASE=${DB_NAME}
      - PGSSLMODE=${DB_SSLMODE}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: cockroachdb/cockroach:${DB_IMAGE_TAG}
    networks:
      - app-network
    ports:
      - "${DB_PORT}:${DB_PORT}"
      - "${DB_CONSOLE_PORT}:8080"
    volumes:
      - db-data:/cockroach/cockroach-data
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  app-network:
    driver: bridge